---
code: 415
internalName: DuplicateExceptionViolation
title: "Found duplicate exception: \U0001F130"
---

{% import "macros.html" as macros with context %}

Forbid the same exception class in multiple `except` blocks.

  - Reasoning:  
    Having the same exception name in different blocks means that
    something is not right: since only one branch will work. Another one
    will always be ignored. So, that is an error.

  - Solution:  
    Use unique exception handling rules.

Example:

    # Correct:
    try:
        ...
    except ValueError:
        ...
    
    # Wrong:
    try:
        ...
    except ValueError:
        ...
    except ValueError:
        ...

<div class="versionadded">

0.6.0

</div>

<div class="versionchanged">

0.11.0

</div>