---
code: 415
title: 'Found duplicate exception: {0}'
---


Forbid the same exception class in multiple ``except`` blocks.

Reasoning:
    Having the same exception name in different blocks means
    that something is not right: since only one branch will work.
    Another one will always be ignored. So, that is an error.

Solution:
    Use unique exception handling rules.

Example::

    # Correct:
    try:
        ...
    except ValueError:
        ...

    # Wrong:
    try:
        ...
    except ValueError:
        ...
    except ValueError:
        ...

.. versionadded:: 0.6.0
.. versionchanged:: 0.11.0